language: node_js
node_js:
  - '10'
addons:
  apt:
    packages:
      - libsecret-1-0
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
  - set -e
  - yarn setup:submodule
  - yarn build:jslib
  - yarn build:keys
after_success:
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_REPO_SLUG = "cozy/cozy-keys-lib" && yarn semantic-release
global:
  env:
    - secure: 'nBBPG+lGPNohjZabCO7V4tkTcYaUJysDVgVcWi++3xPe7JIL+LfOYuddV5h7oIcYpS0a+qy/VlZI4SSgh1/VzzXDgyWU3YC/bOjOajte8Z6KOEZ+2UDZZcMHjrAzjuXEhUgejLwppKz9GunSw0m6077sXJynv+xrwTvzFZVthjU+ueZ629fH2qNzgnha8RwSwQE2FgH+xW2SqVAo4EnaS8VD9nvxKA3HPFpRfaJGPkCLYbnqeocOfcCNimVIFbZ54OKUW7KRXAnNa2S/mNqExfX/HKplzb1vW9+hdp2zIBiJRbN+uF5Mq5/gs2EboJifZt8VNasJE0AAX5nPZG9F6ckVAhBM79wqwHBZqOpLmA6clq4QEtNRBP2e+uazeXqkY33enTWvT9KcSwXRl/tThD0zSHGdf0/ZtDINvmXAYGkOHjGBAymvXk/TVd4164skcmeP9WmpMA5c0m8eLkA32UMEheBP0RI6A5Wzl0+LQx2VmyAq+Ih0++a8mtnDBvUsnGPP+DVpnmC1CJ0YfypKmEI92X+F06qqMWrgioeq7t/WvFpMrgcLzYOHmWJwJgZVpYqwNvh0ocQOV35qsE3jHEhn2RRrdiTJd7nGkdL04WgRhvt7Kob1k0nLHm0zwBP/s4LzObavLFzdQJrGHkD6j3wUAD663/8TExUZWa0yjfo=' # NPM_TOKEN
