language: node_js
node_js:
  - '10'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - deadsnakes
    packages:
      - g++-4.8
      - python3.5
cache:
  yarn: true
  directories:
    - node_modules
script:
  - set -e
  - yarn setup:submodule
  - yarn build:jslib
  - yarn build:keys
after_success:
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_REPO_SLUG = "cozy/cozy-keys-lib" && yarn semantic-release
global:
  env:
    - secure: 'nBBPG+lGPNohjZabCO7V4tkTcYaUJysDVgVcWi++3xPe7JIL+LfOYuddV5h7oIcYpS0a+qy/VlZI4SSgh1/VzzXDgyWU3YC/bOjOajte8Z6KOEZ+2UDZZcMHjrAzjuXEhUgejLwppKz9GunSw0m6077sXJynv+xrwTvzFZVthjU+ueZ629fH2qNzgnha8RwSwQE2FgH+xW2SqVAo4EnaS8VD9nvxKA3HPFpRfaJGPkCLYbnqeocOfcCNimVIFbZ54OKUW7KRXAnNa2S/mNqExfX/HKplzb1vW9+hdp2zIBiJRbN+uF5Mq5/gs2EboJifZt8VNasJE0AAX5nPZG9F6ckVAhBM79wqwHBZqOpLmA6clq4QEtNRBP2e+uazeXqkY33enTWvT9KcSwXRl/tThD0zSHGdf0/ZtDINvmXAYGkOHjGBAymvXk/TVd4164skcmeP9WmpMA5c0m8eLkA32UMEheBP0RI6A5Wzl0+LQx2VmyAq+Ih0++a8mtnDBvUsnGPP+DVpnmC1CJ0YfypKmEI92X+F06qqMWrgioeq7t/WvFpMrgcLzYOHmWJwJgZVpYqwNvh0ocQOV35qsE3jHEhn2RRrdiTJd7nGkdL04WgRhvt7Kob1k0nLHm0zwBP/s4LzObavLFzdQJrGHkD6j3wUAD663/8TExUZWa0yjfo=' # NPM_TOKEN
    - secure: 'WiRCpkWWgKXAauzE1RvnZP6DE1UFvOOryS2sUTMVE6baqZpXdBxLAzSQ5tZyVU0FG2bGFvCqL8qgOM7BuR0pTjHq8Wt/OOrFDnJVbJpgu5Xvf/b6nVNuPV5cX96k9h//MnkMgXxGBuhbYT6zRLm8Oam//XkUP9uuMy4NST6tINtUALG46oouZpmLk0dVFY30vNwokORl0LBfC+cgEOHmMuDkhNdkSrzdLwNeit/e4gSTE5Ws/Rw2iwyoqGQW2yZtMIKX+dVRu5SFqYoiVSLdldP/1uo7CMVFkJECOCrVXFEN/Qx2YPqC1ni5qciLyiQhuGfn869k9INi8pzGDrfg+/5oUTSqgZrpp8FbUTyzDdgefKH6MvYk+ECqG+TwTLC5T1DCvgOoEZw6dH+rR2mSJVBtrNInvj/FynRI5v0M+PjdBfMenlR/UFYAwhEdWaCw7N1XxPAXOEaqov9ZepdNXyyeG3VV6ACtsbHfYCxfhGQnVYEuEfpll0StbNR+LZfXavcG8jEcwW41daXOtwnnqay+b+LDSP/pKiwJZ8tIRs6wNXax+PiOH+fcNCaJqbn0fq4gysIJN0qj0NFSfqe3+xekvtMIO25AAyNtiLucgWrJj7EO/9x7DyK2YCYiYug1s80Nvzuc2JZBB3WIP1X3hklIwS31seexniMEeVuBaRw=' # GH_TOKEN
